version: "3"
services:
  username-gen-easy-app:
    build: ./app
    ports:
      - 61444:80
    environment:
      - FLAG=flag{i_l0v3_d0m_XSS}

  username-gen-easy-admin:
    build: ./admin
    privileged: true
    ports:
      - 61445:8000
    restart: always
