version: '3.4'

services:
  rce:
    image: rce
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 61333:5000
    environment:
      - FLAG=flag{next_time_ill_use_a_library}